### ISSUE TITLE
Add the possibility to highlight specific lines

### ISSUE THREAD

**Issue by Thooms** [Thooms/PPaste#8]
To just like GitHub does.
- We can add a parameter to a paste URL (`/paste/foo123&ln=1-2+42` for instance)
- We can pass the `hl_lines` flag to Pygments when coloring the paste text

**Comment by MrChoclate** [comment]
What do you think about ln=1&ln=2&ln=3 ? Can flask handle this correctly?

**Comment by Thooms** [comment]
I don't think this is a good idea :) I'd rather have some kind of DSL to specify ranges and specific lines!

**Comment by MrChoclate** [comment]
So you want to deal with this regexp: 

``` python
r"\d+|(\d+-\d+)(\+\d+|(\d+-\d+))*"
```

parse it and get a list of lines?

**Comment by Thooms** [comment]
Something like that, yeah :)
